version: "3.9"


services:

#  mysql:
#    image: mysql:latest
#    container_name: db_mysql
#    restart: always
#    environment:
#      MYSQL_DATABASE: db_rent_dashboard_mvp
##      MYSQL_USER: rent
#      MYSQL_ROOT_PASSWORD: PouriaCloner313
##      MYSQL_ALLOW_EMPTY_PASSWORD: PouriaCloner313
##      MYSQL_RANDOM_ROOT_PASSWORD: PouriaCloner313
#    expose:
#      - 3306
#    volumes:
#      - my-db:/var/lib/mysql
#    networks:
#      - main
  postgres:
    container_name: postgres
    image: postgres:15.1
    environment:
      - POSTGRES_DB=db_rent_dashboard_mvp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Sedreh&313
    networks:
      - main
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data


  pgAdmin:
    image: dpage/pgadmin4:6.16
    container_name: pgAdmin
    ports:
      - "8001:80"
    volumes:
      - pgAdmin_data:/var/lib/pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=sedrehgroup@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Sedreh&313
    depends_on:
      - postgres
    networks:
      - main

  api_django:
    build:
      context: ./django
    command: sh -c "python manage.py makemigrations --noinput
      && python manage.py migrate
      && gunicorn --reload RentDashboardMVP.wsgi --bind 0.0.0.0:8000"
    container_name: api_django
    depends_on:
      - postgres
    expose:
      - 8000
    environment:
      - DB_HOST=postgres
      - DB_NAME=db_rent_dashboard_mvp
      - DB_USER=postgres
      - DB_PASS=Sedreh&313
      - DB_PORT=5432
      - DB_SCHEMA=public
      - ALLOW_ORIGIN=http://localhost:3000
    networks:
      - main
    volumes:
      - ./django:/api_django
    restart: always

  nginx:
    container_name: nginx
    command: nginx -g 'daemon off;'
    depends_on:
      - api_django
    image: nginx:latest
    networks:
      - main
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro


networks:
  main:

volumes:
  postgres_data:
  pgAdmin_data: