# Generated by Django 4.1.3 on 2022-11-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rent_delete_lease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
