# Generated by Django 4.1.3 on 2022-11-24 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_national_code_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditionalinformation',
            name='address',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='useradditionalinformation',
            name='birth_day',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='useradditionalinformation',
            name='certificate_country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='useradditionalinformation',
            name='certificate_county',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='useradditionalinformation',
            name='certificate_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='useradditionalinformation',
            name='certificate_province',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='useradditionalinformation',
            name='certificate_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='useradditionalinformation',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='useradditionalinformation',
            name='county',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='useradditionalinformation',
            name='education',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='useradditionalinformation',
            name='father_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='useradditionalinformation',
            name='latin_first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useradditionalinformation',
            name='latin_last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useradditionalinformation',
            name='marriage',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='useradditionalinformation',
            name='personal_phone_number',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='useradditionalinformation',
            name='postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='useradditionalinformation',
            name='province',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='useradditionalinformation',
            name='sex',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='useradditionalinformation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
