# Generated by Django 4.1.3 on 2022-11-24 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_useradditionalinformation_birth_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditionalinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
