# Generated by Django 4.1.3 on 2022-11-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_rent_phone_alter_rent_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='rent',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
